### ISSUE TITLE
🐛 `VyperDeployer` Fails in Forking Mode

### ISSUE THREAD

**Issue by Hovooo** [pcaversaccio/snekmate#196]
### Describe the issue:

Vyper Deployer is not working when forking from a real blockchain. 

I tried forking from arbitrum and ethereum mainnet. 

I get the following error:

    ├─ [0] VyperDeployer::deployContract("contracts/vyper/", "ReceiptToken")
    │   └─ ← ()
    └─ ← EvmError: Revert

But when I do not use fork, everything works perfectly as follows:

    ├─ [626407] VyperDeployer::deployContract("contracts/vyper/", "ReceiptToken")
    │   ├─ [0] VM::ffi(["vyper", "contracts/vyper/ReceiptToken.vy"])
    │   ├─ [581004] → new <unknown>@0x104fBc016F4bb334D775a19E8A6510109AC63E00
    │   │   └─ ← 2902 bytes of code
    │   ├─ emit ContractCreation(newContract: 0x104fBc016F4bb334D775a19E8A6510109AC63E00)
    │   └─ ← 0x104fBc016F4bb334D775a19E8A6510109AC63E00
    └─ ← ()

### Code example to reproduce the issue:

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/console.sol";
import "forge-std/Test.sol";

import {IReceiptToken} from "../../contracts/interfaces/vyper/IReceiptToken.sol";
import {VyperDeployer} from "../../lib/utils/VyperDeployer.sol"; // it's a copy of your VyperDeployer.sol

contract ForkTest is Test {

IReceiptToken public receiptTokenReference;
VyperDeployer vyperDeployer = new VyperDeployer();

function setUp() public {
        vm.createSelectFork(vm.rpcUrl("arbitrum"));

        receiptTokenReference =
            IReceiptToken(vyperDeployer.deployContract("contracts/vyper/", "ReceiptToken"));

}
```

### Version:

0.2.16+commit.59e1bdd

**Comment by pcaversaccio** [comment]
You use a very old Vyper version, which has a critical vulnerability (see [here](https://github.com/vyperlang/vyper/releases/tag/v0.2.16)). Can you please upgrade to use at least version `0.3.7` and retry?

**Comment by Hovooo** [comment]
Hey Pascal, thank you so much for your quick response. 

I tried using version `0.3.8`, but it didn't change anything. 

Still everything works perfectly without forking and reverts with it.

Maybe there is something else I could try?

**Comment by pcaversaccio** [comment]
> Hey Pascal, thank you so much for your quick response. 
> 
> I tried using version `0.3.8`, but it didn't change anything. 
> 
> Still everything works perfectly without forking and reverts with it.
> 
> Maybe there is something else I could try?

Can you share with me the full repository so I can debug it myself?

**Comment by pcaversaccio** [comment]
Ah wait you used `0.3.8` which uses the EVM version `shanghai` as default that is not supported by Arbitrum. Can you use `0.3.7` please.

**Comment by pcaversaccio** [comment]
Or alternatively, you can use [this](https://github.com/pcaversaccio/snekmate/blob/main/lib%2Futils%2FVyperDeployer.sol#L195) instead with `"paris"` instead together with `0.3.8`.

**Comment by Hovooo** [comment]
Sharing repository is a little difficult as it's really huge and is not open sourced yet, so it would take me forever to replicate the repository for sharing purposes, but I have found something interesting. 

So if I compile vyper contract without fork, I get the bytecode and then, I have success deploying contract using the provided bytecode: 

```

        bytes memory bytecode = "0x611b7.........8000b";

        address liquidityGaugeReference;

        assembly {
            liquidityGaugeReference := create(0, add(bytecode, 0x20), mload(bytecode))
        }

```


Then I thought maybe I can just get the bytecode and use it for deployment in the fork, I wrote this function in your VyperDeployer: 

```
    function getBytecode(string calldata path, string calldata fileName)
        public
        returns (bytes memory bytecode)
    {
        string[] memory cmds = new string[](2);
        cmds[0] = "vyper";
        cmds[1] = string.concat(path, fileName, ".vy");

        /**
         * @dev Compile the Vyper contract and return the bytecode.
         */
        bytecode = cheatCodes.ffi(cmds);
    }

```


And after that everything failed again, so I guess the problem is just in compilation process.

**Comment by Hovooo** [comment]
> Ah wait you used `0.3.8` which uses the EVM version `shanghai` as default that is not supported by Arbitrum. Can you use `0.3.7` please.

There's a problem with installing that particular version of vyper, that's why I used `0.3.8`

> Or alternatively, you can use [this](https://github.com/pcaversaccio/snekmate/blob/main/lib%2Futils%2FVyperDeployer.sol#L195) function instead with `"paris"` together with `0.3.8`.

this didn't help, I still get 

    ├─ [0] VyperDeployer::deployContract("contracts/vyper/", "LiquidityGauge", 0x, "paris", true)
    │   └─ ← ()
    └─ ← EvmError: Revert

**Comment by pcaversaccio** [comment]
> > Ah wait you used `0.3.8` which uses the EVM version `shanghai` as default that is not supported by Arbitrum. Can you use `0.3.7` please.
> 
> There's a problem with installing that particular version of vyper, that's why I used `0.3.8`
> 
> > Or alternatively, you can use [this](https://github.com/pcaversaccio/snekmate/blob/main/lib%2Futils%2FVyperDeployer.sol#L195) function instead with `"paris"` together with `0.3.8`.
> 
> this didn't help, I still get 
> 
>     ├─ [0] VyperDeployer::deployContract("contracts/vyper/", "LiquidityGauge", 0x, "paris", true)
>     │   └─ ← ()
>     └─ ← EvmError: Revert
> 
> 
> 
> 
> 
> 

Ok let me setup my own reproduction example. It might be that it's a Foundry bug due to createFork + ffi cheatcode. In that case you would need to open in their repo an issue. But let me first check.

**Comment by pcaversaccio** [comment]
Ok I quickly reproduced your issue locally and I know what is wrong. The issue is that you first deploy locally the `VyperDeployer` and after that you select a fork, meaning that the `VyperDeployer` is not present on the fork state and thus any call to the `VyperDeployer` address will revert. You can fix it like this:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/console.sol";
import "forge-std/Test.sol";

import {IReceiptToken} from "../../contracts/interfaces/vyper/IReceiptToken.sol";
import {VyperDeployer} from "../../lib/utils/VyperDeployer.sol"; // it's a copy of your VyperDeployer.sol

contract ForkTest is Test {

IReceiptToken public receiptTokenReference;
VyperDeployer private vyperDeployer;

function setUp() public {
     vm.createSelectFork(vm.rpcUrl("arbitrum"));
     vyperDeployer = new VyperDeployer(); // Deploy the `VyperDeployer` _after_ fork selection!
     receiptTokenReference = IReceiptToken(vyperDeployer.deployContract("contracts/vyper/", "ReceiptToken"));
}
```

Will close this issue as resolved (please re-open if it doesn't solve your issue!).

**Comment by Hovooo** [comment]
Oh, sure 

Thanks a lot for your help!
