### ISSUE TITLE
🐛 Unable to Call `distribute_token` in `BatchDistributor` via Etherscan

### ISSUE THREAD

**Issue by YoungPhlo** [pcaversaccio/snekmate#210]
### Describe the issue:

I get a weird error when trying to use `distribute_token` via [Etherscan UI](https://goerli.etherscan.io/address/0xd512ce9248d509a9451530f31c8bf054b1d242eb#writeContract)

![chrome_ubj3pjKpbK](https://github.com/pcaversaccio/snekmate/assets/90307961/de32fc5d-a44d-4721-897c-dcdd5276d702)

The error says: `invalid tuple value (argument="tuple", value="{txns: [\"0x7a32B409353930e6650008e94F64bE536a79055B\"", code=INVALID_ARGUMENT, version=abi/5.7.0)`

The address ending in `a79055B` is a regular EOA on Goerli Testnet

`token` input is `0xc4bCC48989803cC70415C1c513113a350330a8E8`, an ERC20
`data` input is the `Batch` struct - `{txns: [address, amount]}`

Everything works as intended when I use `distribute_ether` - [here's a successful transaction.](https://goerli.etherscan.io/tx/0x6ca47cbba0724b7598280abd2202e518786bed3d6508746a4bc7168a43813979)
I use the same `Batch` struct format of `{txns: [address, amount]}` then I click the Write button and complete the transaction via Metamask.

When I click the Write button for `distribute_token` I get the red invalid tuple value error.

I have tried a bunch of different variations of the tuple: with and without quotations, DynArray minus the outer tuple, double checking the ABI, cache flush + hard refresh... even launching slight variations of `BatchDistributor.vy`

I was initially experimenting with different pragma versions and thought maybe having the following versions caused a weird error:
```
#pragma version ^0.3.10
#pragma optimize gas
#pragma evm-version shanghai
```

But even when I remove these and deploy a new contract I get the same error.

I also tried to interact with the contract via ApeworX. My CLI shows a different error description, but ultimately leads to the same result.

![Code_Mv3NSj4i7h](https://github.com/pcaversaccio/snekmate/assets/90307961/323f4aec-6da3-4df6-bfe7-04e32f9a020f)

Command:
```
contract.distribute_token("0xc4bCC48989803cC70415C1c513113a350330a8E8", airdrop_list, sender=wallet)
```

Error:
```py
ERROR: (ContractLogicError) Transaction failed.
```

I am very new to Vyper and it took me awhile to figure out how to properly format the structs, DynArray is new to me.
I see the two `assert` at the bottom of `distribute_token` but not sure how to follow what happens with the toke transfers after that.

What am I doing wrong?

### Code example to reproduce the issue:
```py
#pragma version ^0.3.10
#pragma optimize gas
#pragma evm-version shanghai

"""
@title Batch ERC20 Tokens
@custom:contract-name BatchDistributor
@license GNU Affero General Public License v3.0 only
@author pcaversaccio
@notice Initial airdrop test for distributing ether and ERC-20 tokens to a predefined batch of recipient addresses.
"""


# @dev We import the `ERC20` interface, which is a
# built-in interface of the Vyper compiler.
from vyper.interfaces import ERC20


# @dev Transaction struct for the transaction payload.
struct Transaction:
    recipient: address
    amount: uint256


# @dev Batch struct for the array of transactions.
struct Batch:
     txns: DynArray[Transaction, max_value(uint8)]


@external
@payable
def __init__():
    """
    @dev To omit the opcodes for checking the `msg.value`
         in the creation-time EVM bytecode, the constructor
         is declared as `payable`.
    """
    pass


@external
@payable
@nonreentrant("lock")
def distribute_ether(data: Batch):
    """
    @dev Distributes ether, denominated in wei, to a
         predefined batch of recipient addresses.
    @notice In the event that excessive ether is sent,
            the residual amount is returned back to the
            `msg.sender`.

            Furthermore, it is important to note that an
            external call via `raw_call` does not perform
            an external code size check on the target address.
    @param data Nested struct object that contains an array
           of tuples that contain each a recipient address &
           ether amount in wei.
    """
    for txn in data.txns:
        # A low-level call is used to guarantee compatibility
        # with smart contract wallets. As a general pre-emptive
        # safety measure, a reentrancy guard is used.
        raw_call(txn.recipient, b"", value=txn.amount)

    if (self.balance != empty(uint256)):
        # IMPORTANT: Any wei amount previously forced into this
        # contract (e.g. by using the `SELFDESTRUCT` opcode) will
        # be part of the refund transaction.
        raw_call(msg.sender, b"", value=self.balance)


@external
def distribute_token(token: ERC20, data: Batch):
    """
    @dev Distributes ERC-20 tokens, denominated in their corresponding
         lowest unit, to a predefined batch of recipient addresses.
    @notice To deal with (potentially) non-compliant ERC-20 tokens that do have
            no return value, we use the kwarg `default_return_value` for external
            calls. This function was introduced in Vyper version 0.3.4. For more
            details see:
            - https://github.com/vyperlang/vyper/pull/2839,
            - https://github.com/vyperlang/vyper/issues/2812,
            - https://medium.com/coinmonks/missing-return-value-bug-at-least-130-tokens-affected-d67bf08521ca.
            Note: Since we cast the token address into the official ERC-20 interface,
            the use of non-compliant ERC-20 tokens is prevented by design. Nevertheless,
            we keep this guardrail for security reasons.
    @param token ERC-20 token contract address.
    @param data Nested struct object that contains an array
           of tuples that contain each a recipient address &
           token amount.
    """
    total: uint256 = empty(uint256)
    for txn in data.txns:
        total += txn.amount

    # It is important to note that an external call via interface casting
    # always performs an external code size check on the target address unless
    # you add the kwarg `skip_contract_check=True`. If the check fails (i.e.
    # the target address is an EOA), the call reverts.
    assert token.transferFrom(msg.sender, self, total, default_return_value=True), "BatchDistributor: transferFrom operation did not succeed"

    for txn in data.txns:
        assert token.transfer(txn.recipient, txn.amount, default_return_value=True), "BatchDistributor: transfer operation did not succeed"
```

### Version:

`0.3.10+commit.9136169`
```
Installed Plugins
  alchemy      0.7.1
  ens          0.7.0
  etherscan    0.7.1
  template     0.7.0
  tokens       0.7.1
  vyper        0.7.0
```

**Comment by pcaversaccio** [comment]
@YoungPhlo I quickly took a look and this is clearly _not_ a bug in the `BatchDistributor` contract nor the function `distribute_token`, but most probably how Etherscan encodes nested tuples and there seems to be a bug on their end (I can replicate your issue).

In order to successfully call the function `distribute_token`, you need to `approve` the amount to be distributed to the `BatchDistributor` contract in the first step. Example: https://goerli.etherscan.io/tx/0xc105d69044c109e0a6982cb22a89b54b9e91a4058dc27fa6c774d2bb21ea198e

Second, you have to encode the payload like this in the Remix UI (use the Vyper plugin & load the deployed contract to interact with in the deploy tab):

```console
[[["0x9F3f11d72d96910df008Cfe3aBA40F361D2EED03", 5000000000000000000],["0x3854Ca47Abc62A3771fE06ab45622A42C4A438Cf", 5000000000000000000]]]
```

The first `[]` is to indicate it's a tuple, the second `[]` is for the struct array `Batch`, and the third `[]` for the struct payload `Transaction`.

![image](https://github.com/pcaversaccio/snekmate/assets/25297591/50795de7-4d14-4972-a499-45a68a7e5cb5)

Example transaction: https://goerli.etherscan.io/tx/0xb7c38c30154e2bbe86bb5e42247c58aaba97cec4fc4aaf5d19d0ab3440330e03.

**Comment by pcaversaccio** [comment]
So I informed Etherscan about the bug and will close this issue accordingly. Furthermore, your ApeworX interaction fails since you didn't approve anything to the `BatchDistributor` and thus it can't distribute any tokens. Please first `approve` them like I showed in my example above. Feel free to comment if you have further issues.
