### ISSUE TITLE
🐛 Cannot Compile `erc721`

### ISSUE THREAD

**Issue by rafael-abuawad** [pcaversaccio/snekmate#258]
### Describe the issue:

Im trying to create a NFT project using the new snekmate (Vyper 0.4.0) but for some reason the `uses` keyword triggers an error.

```bash
Error compiling: contracts/tokens/erc721.vy
vyper.exceptions.InitializerException: module `contracts/auth/ownable.vy` is used but never initialized!
```

The only solution I found was to:

1. Change it from `uses` to `initializes`
```diff
# @dev We import and use the `ownable` module.
from ..auth import ownable
- uses: ownable
+ initializes: ownable
```

2. Add the ownable initializer in the constructor:
```diff
# constructor
+    ownable.__init__()
```

After that, running `ape compile` and `vyper contracts/tokens/erc721.vy` works as expected.

### Code example to reproduce the issue:

[This is my repo](https://github.com/rafael-abuawad/onchain-real-estate)

### Version:

```bash
$ vyper --version
0.4.0+commit.e9db8d9
```

```bash
$ ape --version
0.8.5
```

### Relevant log output:

```Shell
InitializerException:module `contracts/auth/ownable.vy` is used but never initialized!

  (hint: add `initializes: ownable` to `/workspaces/dev-container/portfolio/onchain-real-estate/contracts/tokens/erc721.vy`)

  contract "/workspaces/dev-container/onchain-real-estate/contracts/tokens/erc721.vy:101", line 101:0 
       100 from ..auth import ownable
  ---> 101 uses: ownable
  ---------^
       102
. However, there is a source file named 'erc721.vy', did you mean to reference a contract name from this source file?
```

**Comment by pcaversaccio** [comment]
Hey @rafael-abuawad thanks for opening an issue but this is not a bug but a feature! Let me explain: In my [`README` section](https://github.com/pcaversaccio/snekmate/tree/main#-usage) for module usage, I explicitly state the following:
> Thus, many of the 🐍 snekmate contracts do not compile independently, but you must `import` and `initializes` them.

Most of the stateful 🐍 snekmate contracts cannot be compiled on their own; they must be `import`ed and `initializes`ed within the main developer's contract. Think of them as `abstract` contracts in Solidity. This design requires developers to comprehend the composition of imported modules and the implications for storage layout. In short, developers must thoroughly understand what they're doing!

As also mentioned in the [`README`](https://github.com/pcaversaccio/snekmate/tree/main#-usage), each module contract comes with a corresponding mock contract located in the `mock/` directory within the respective contract subdirectory. For your specific case, you can find an exemplary mock [here](https://github.com/pcaversaccio/snekmate/blob/main/src/snekmate/tokens/mocks/erc721_mock.vy).

Eventually, all 🐍 snekmate contracts are also tested through `ape` compilation. You can see in the [configuration file](https://github.com/pcaversaccio/snekmate/blob/main/ape-config.yaml) how I exclude all non-mock contracts from compilation for the reasons explained above.

**Comment by rafael-abuawad** [comment]
Thanks @pcaversaccio for the quick response!

Got it, so for now, stateful 🐍 Snekmate contracts must be imported and initialized within the main developer's contract. I will do a deep dive into composition in Vyper

**Comment by pcaversaccio** [comment]
> Thanks @pcaversaccio for the quick response!
> 
> Got it, so for now, stateful 🐍 snekmate contracts must be imported and initialized within the main developer's contract. I will do a deep dive into composition in Vyper

FWIW, I just released 🐍 snekmate [`v0.1.0`](https://github.com/pcaversaccio/snekmate/releases/tag/v0.1.0)!

**Comment by rafael-abuawad** [comment]
Wow! That was insane, amazing!

Quick question: in Ape, how can I use the following syntax?
```vy
from snekmate.tokens import erc20
```
Do I need to install Snekmate using pip?

**Comment by pcaversaccio** [comment]
> Wow! That was insane, amazing!
> 
> Quick question: in Ape, how can I use the following syntax?
> 
> ```vyper
> from snekmate.tokens import erc20
> ```
> 
> Do I need to install Snekmate using pip?

yes simply do:

```
pip install snekmate
```

and you're good to go. When using the [Vyper CLI](https://docs.vyperlang.org/en/stable/compiling-a-contract.html#vyper-cli-command), the search path defaults to the current working directory, plus the python [syspath](https://docs.python.org/3.11/library/sys.html#sys.path). So it will automatically find `snekmate` at compile-time.

**Comment by pcaversaccio** [comment]
> > Wow! That was insane, amazing!
> > Quick question: in Ape, how can I use the following syntax?
> > ```vyper
> > from snekmate.tokens import erc20
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do I need to install Snekmate using pip?
> 
> yes simply do:
> 
> ```
> pip install snekmate
> ```
> 
> and you're good to go. When using the [Vyper CLI](https://docs.vyperlang.org/en/stable/compiling-a-contract.html#vyper-cli-command), the search path defaults to the current working directory, plus the Python [syspath](https://docs.python.org/3.11/library/sys.html#sys.path). So it will automatically find `snekmate` at compile-time.

I just tested with the latest `ape` version and it seems that this is not yet supported. I will ping the ape team to support the Python `sys.path`.

**Comment by rafael-abuawad** [comment]
Thank you @pcaversaccio! My current approach is to copy the files that I need by hand, in older snekmate versions that was cool, but now with composition available that doesn't seem right, it works, but it doesn't seem right

**Comment by pcaversaccio** [comment]
> Thank you @pcaversaccio! My current approach is to copy the files that I need by hand, in older snekmate versions that was cool, but now with composition available that doesn't seem right, it works, but it doesn't seem right

It's in the works already: https://github.com/ApeWorX/ape/pull/2163

So for now, in `ape`, as a workaround, you can invoke `pip install snekmate -t .` in your working directory for contracts (e.g. `src/`) and after that you can also simply import it like that (since `ape` finds it now):

```vy
from snekmate.tokens import erc20
```

if you need to go to a parent directory or higher, you can simply add `..`, `...` and so forth:

```vy
from ..snekmate.tokens import erc20
```

**Comment by pcaversaccio** [comment]
> > Thank you @pcaversaccio! My current approach is to copy the files that I need by hand, in older snekmate versions that was cool, but now with composition available that doesn't seem right, it works, but it doesn't seem right
> 
> It's in the works already: [ApeWorX/ape#2163](https://github.com/ApeWorX/ape/pull/2163)
> 
> So for now, in `ape`, as a workaround, you can invoke `pip install snekmate -t .` in your working directory for contracts (e.g. `src/`) and after that you can also simply import it like that in your main contract (since `ape` finds it now):
> 
> ```vyper
> from snekmate.tokens import erc20
> ```
> 
> if you need to go to a parent directory or higher, you can simply add `..`, `...` and so forth:
> 
> ```vyper
> from ..snekmate.tokens import erc20
> ```

Update: It will be possible with the new to-be-released `ape` version: https://github.com/ApeWorX/ape/pull/2163.
