### ISSUE TITLE
[Feature-Request]: Add strict ERC1271 Signature Checking for `SignatureChecker.vy`

### ISSUE THREAD

**Issue by YamenMerhi** [pcaversaccio/snekmate#50]
### Motivation

In the current `SignatureChecker`, there is support to check if a signature is valid with the `is_valid_signature_now(..)` function that checks the following:
- If the `hash` and `signature` recover an address that is the same as the `signer`, it returns true.
- When it's not the case, it calls `is_valid_signature(..)` on the `signer` assuming it's a contract. 

What would be a great addition to the library is to have another internal function that checks if a signature is valid with **ERC1271** only. So calling `is_valid_signature(..)` directly on the signer implementing ERC1271.

This function will be useful for functions that want to interact only with wallets such as argent, gnosis, etc .. and check the signature **only via ERC1271**. 

Then this function can be re-used in `is_valid_signature_now(..)`.

### Details

Developers can interact with other smart contract wallets by calling `is_valid_signature(..)` function directly. Still, they need to handle the return value, so the new function can be a wrapper named `is_valid_ERC1271_signature_now(address,bytes32,bytes[65])` that calls `is_valid_signature(..)` on the address with the hash and the signature and don't revert if the function doesn't exist and return true or false, depending if the function returns the `isValidSignature.selector`. Exactly like what the code does in the second part of the `is_valid_signature_now(..)` function.

If you find this addition relevant, I can work on creating the new function (splitting the `is_valid_signature_now(..)` function into a new one).

### Code example that solves the feature:

It would be mostly taking this part of the function to a new function (`is_valid_ERC1271_signature_now(..)`) that can be re-used in `is_valid_signature_now(..)`
```vy
# Second check: EIP-1271 case.
    return_data: Bytes[32] = \
        raw_call(signer, _abi_encode(hash, signature, method_id=IERC1271_ISVALIDSIGNATURE_SELECTOR), max_outsize=32, is_static_call=True)
    return ((len(return_data) == 32) and (convert(return_data, bytes32) == convert(IERC1271_ISVALIDSIGNATURE_SELECTOR, bytes32)))
```

**Comment by pcaversaccio** [comment]
@YamenMerhi thanks for sharing the details about your idea. Your idea addresses the composability of the code. While I do see the intent of your issue, I don't think this is the right approach to solve this. Let me explain why:

#### Case 1: Only ECDSA Support

Devs can use the [`ECDSA`](https://github.com/pcaversaccio/snekmate/blob/main/src/utils/ECDSA.vy) contract.

#### Case 2: Support of ECDSA & EIP-1271

Devs can use the [`SignatureChecker`](https://github.com/pcaversaccio/snekmate/blob/main/src/utils/ECDSA.vy) contract.

#### Case 3: Only EIP-1271 Support

Devs can use the [`SignatureChecker`](https://github.com/pcaversaccio/snekmate/blob/main/src/utils/ECDSA.vy) contract with a simple `is_contract` check beforehand and making the function `_is_valid_signature_now` `internal` or simply using the `external` function via a simple interface:


*Option 1:* `internal` function approach 
```vy
@external
@view
def is_valid_ERC1271_signature_now(signer: address, hash: bytes32, signature: Bytes[65]) -> bool:
    if (signer.is_contract):
        return self._is_valid_signature_now(signer, hash, signature)
    return False


@internal
@view
def _is_valid_signature_now(signer: address, hash: bytes32, signature: Bytes[65]) -> bool:
    # First check: ECDSA case.
    recovered: address = self._recover_sig(hash, signature)
    if (recovered == signer):
        return True

    # Second check: EIP-1271 case.
    return_data: Bytes[32] = \
        raw_call(signer, _abi_encode(hash, signature, method_id=IERC1271_ISVALIDSIGNATURE_SELECTOR), max_outsize=32, is_static_call=True)
    return ((len(return_data) == 32) and (convert(return_data, bytes32) == convert(IERC1271_ISVALIDSIGNATURE_SELECTOR, bytes32)))
```

*Option 2:* `external` function approach

```vyper
interface SignatureChecker:
    def is_valid_signature_now(signer: address, hash: bytes32, signature: Bytes[65]) -> bool: view


@external
@view
def is_valid_ERC1271_signature_now(signer: address, hash: bytes32, signature: Bytes[65]) -> bool:
    if (signer.is_contract):
        return SignatureChecker(self).is_valid_signature_now(signer, hash, signature)
    return False
```

The contract `SignatureChecker` is a superset of `ECDSA` & `EIP-1271` and is already composable if you need to strictly make a `EIP-1271` check. Would agree with this or why exactly do you see a specific need to solve this via a separate `internal` function?

**Comment by pcaversaccio** [comment]
I think after reflecting on your proposal, it would make sense to add two functions:
- `is_valid_ERC1271_signature_now` (`external`) that simply calls the following `internal` function
- `_is_valid_ERC1271_signature_now` (`internal`)

`_is_valid_ERC1271_signature_now` can be re-used in `_is_valid_signature_now``.

```vyper
@external
@view
def is_valid_ERC1271_signature_now(signer: address, hash: bytes32, signature: Bytes[65]) -> bool:
    return self._is_valid_ERC1271_signature_now(signer, hash, signature)


@internal
@view
def _is_valid_ERC1271_signature_now(signer: address, hash: bytes32, signature: Bytes[65]) -> bool:
    return_data: Bytes[32] = \
        raw_call(signer, _abi_encode(hash, signature, method_id=IERC1271_ISVALIDSIGNATURE_SELECTOR), max_outsize=32, is_static_call=True)
    return ((len(return_data) == 32) and (convert(return_data, bytes32) == convert(IERC1271_ISVALIDSIGNATURE_SELECTOR, bytes32)))


@external
@view
def is_valid_signature_now(signer: address, hash: bytes32, signature: Bytes[65]) -> bool:
    # First check: ECDSA case.
    recovered: address = self._recover_sig(hash, signature)
    if (recovered == signer):
        return True

    # Second check: EIP-1271 case.
    return self._is_valid_ERC1271_signature_now(signer, hash, signature)
```

Feel free to open a PR on that including the necessary test cases.

**Comment by YamenMerhi** [comment]
@pcaversaccio Exactly, will create the PR for it soon 👍

**Comment by pcaversaccio** [comment]
awesome thx
