### ISSUE TITLE
Revert in EIP-1271 `SignatureChecker`

### ISSUE THREAD

**Issue by YamenMerhi** [pcaversaccio/snekmate#64]
### What this issue is about ?
Looking at the current implementation of `is_valid_ERC1271_signature_now(..)`, we can see that the return value is always checked to be the magic value in order to return true, otherwise, the function should return false. 

This is the same behavior implemented in OpenZeppelin's SignatureChecker library.

The only difference is that in the current implementation in vyper, if you call `is_valid_ERC1271_signature_now(..)` on a contract that doesn't implement `isValidSignature(..)` it will revert the call.

IMO, this should be changed to match the OpenZeppelin behavior, where in case of revert (The signer doesn't implement `isValidSignature(..)` nor have the default function) it should return false. 

Because the whole purpose of having a utility function like this is to abstract the checks that need to be done after an `isValidSignature(..)` call. The person implementing this function just uses it to know whether the signature was valid or invalid and shouldn't expect a revert.

Let me know what do you think.

### Code example to reproduce the issue:

This code snippet:
```vy
return_data: Bytes[32] = \
        raw_call(signer, _abi_encode(hash, signature, method_id=IERC1271_ISVALIDSIGNATURE_SELECTOR), max_outsize=32, is_static_call=True)
    return ((len(return_data) == 32) and (convert(return_data, bytes32) == convert(IERC1271_ISVALIDSIGNATURE_SELECTOR, bytes32)))
```

Needs to be changed to something like this: add the `revert_on_failure` flag, and in the return line add that it should be a `success and ..`
```vy
success: bool = False
    response: Bytes[32] = b""
    success, response = \
    raw_call(signer, _abi_encode(hash, signature, method_id=IERC1271_ISVALIDSIGNATURE_SELECTOR), max_outsize=32, is_static_call=True, revert_on_failure=False)
    return (success and (len(response) == 32) and (convert(response, bytes32) == convert(IERC1271_ISVALIDSIGNATURE_SELECTOR, bytes32)))
```

### Version:

`0.3.7+commit.6020b8b`

**Comment by pcaversaccio** [comment]
@YamenMerhi when I first implemented the functions I thought about it and decided for reverting as a general footgun protection. However, after revisiting the common library implementations (such as the above-mentioned [OpenZeppelin implementation](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/SignatureChecker.sol)), I agree that 🐍 snekmate should also match the current existent behavior of returning `False` instead. I prepared a PR https://github.com/pcaversaccio/snekmate/pull/65 and will merge it probably tomorrow after reviewing again. If you have time, please review it as well.

**Comment by YamenMerhi** [comment]
Done 👍

**Comment by pcaversaccio** [comment]
thx @YamenMerhi
