### ISSUE TITLE
💥 Math Functions

### ISSUE THREAD

**Issue by bout3fiddy** [pcaversaccio/snekmate#72]
### Describe the desired feature:

Add some spicy math functions for Vyper peeps.

**Comment by pcaversaccio** [comment]
Examples: https://github.com/bout3fiddy/tricrypto-ng/blob/ab37f895cae1a5ef2c95b6c7626c47fe8b180b7b/contracts/CurveCryptoMathOptimized3.vy

**Comment by pcaversaccio** [comment]
some functions I want to implement:
- `average`
- `ceil_div` (Returns the ceiling of the division of two numbers.)
- `log2`
- `log10`
- `log256`

**Comment by pcaversaccio** [comment]
For the sake of history, below is a correct but inefficient implementation for `cbrt`:

```vyper
@external
@pure
def cbrt(x: uint256) -> uint256:
    y: uint256 = empty(uint256)
    z: uint256 = empty(uint256)
    value: uint256 = x

    i: uint256 = shift(1, max_value(uint8))
    for _ in range(86):
        y = shift(y, 1)
        z = unsafe_add(unsafe_mul(unsafe_mul(3, y), unsafe_add(y, 1)), 1)
        if (unsafe_div(value, i) >= z):
            value = unsafe_sub(value, unsafe_mul(i, z))
            y = unsafe_add(y, 1)

        i = shift(i, -3)

        if (i == empty(uint256)):
            break

    return y
```
