### ISSUE TITLE
💥 Version `0x00` of EIP-191 in ECDSA Library Implementation

### ISSUE THREAD

**Issue by YamenMerhi** [pcaversaccio/snekmate#78]
### 🧐 Motivation
In the current `ECDSA` library, there is support to construct a message to sign according to the EIP191 Standard with the following:
- The version `0x45` (E) with `to_eth_signed_message_hash(..)` function 
- The version `0x01` with the `to_typed_data_hash(..)` function. 
But we are missing the `0x00` version.

<img width="1460" alt="Screen Shot 2022-10-19 at 10 17 27 PM" src="https://user-images.githubusercontent.com/86341666/196783740-8280e393-8449-4601-ab54-8a31e616531e.png">

### 📝 Details
Version`0x00` version is not that used because people are misusing the standard, they are using the `0x45` version for everything: signing messages for off-chain verification, for smart contract execution based on signatures, which is dangerous.

As people could be easily tricked into signing a normal message, thinking it is for login purposes, and then end up having execution based on this signature, so we should have a different mechanism, then different handling for execution based on signatures, and that's why we should make people use the `0x00` version for this case. + some projects are starting to use it like [xenium](https://github.com/Arachnid/xenium) and the [lsp-smart-contracts](https://github.com/lukso-network/lsp-smart-contracts/blob/v0.8.0/contracts/Custom/EIP191Signer.sol). 

I am suggesting adding a new function `to_data_with_intended_validator` or `to_data_with_intended_validator_hash` to be compatible with the version `0x00` taking 2 parameters, `<address validator>` and `<bytes dataToSign>`.

A library that supports the case: [EIP-191 Signer](https://github.com/lukso-network/tools-eip191-signer).
The Opened issue in OpenZeppelin: [Implement 0x00 version of EIP191 in ECDSA Library](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3772)

If you're okay with it I am happy to open the PR, otherwise, you can close the issue 😄  

### Code example that solves the feature:

```vy
@external
@pure
def to_data_with_intended_validator(validator: address, data_to_sign: Bytes[1024]=b"") -> bytes32:
    """
    @dev Returns an intended validator signed data according to 
    0x00 version of EIP-191.
    @param validator The address validating the signature
    @param struct_hash The data passed to be signed
    @return bytes32 The 32-byte intended validator signed data.
    """
    return keccak256(concat(b"\x19\x00", validator, data_to_sign))
```

**Comment by pcaversaccio** [comment]
@YamenMerhi thanks for raising this point - actually I find it a reasonable addition to 🐍 snekmate. I would actually propose the following solution (ignoring the function docstrings):

```vyper
# @dev A Vyper contract cannot call directly between two `external` functions.
# To bypass this, we can use an interface.
interface compute_intended_validator_hash:
    def to_data_with_intended_validator_hash(validator: address, data: Bytes[1024]) -> bytes32: pure


@external
@view
def to_data_with_intended_validator_hash_self(data: Bytes[1024]=b"") -> bytes32:
    return compute_intended_validator_hash(self).to_data_with_intended_validator_hash(self, data)


@external
@pure
def to_data_with_intended_validator_hash(validator: address, data: Bytes[1024]=b"") -> bytes32:
    return keccak256(concat(b"\x19\x00", convert(validator, bytes20), data))
```

This includes two functions `to_data_with_intended_validator_hash_self` and `to_data_with_intended_validator_hash`, where one uses directly the contract address as validator `address`. If you agree with this, you can PR that, or we can discuss here about alternative solutions.

**Comment by YamenMerhi** [comment]
@pcaversaccio Your code makes sense, will do the PR. 👍 

Also, I don't mind the additional function, as in most of the cases of data with the intended validator, it will be used by some sort of a smart contract account that will validate the signature based on self.

**Comment by pcaversaccio** [comment]
Sounds like a plan 👍
